### ISSUE TITLE
variables shorter than level's data

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#64] opened 2018-01-28 01:06 UTC
We've talked about this before, but right now if you create for example a time series of 18 months long and want a "month name" var you will get an error if you do this:

```
months = add_level(N = 18, month = month.abb)
```

because month.abb is 12 long. Can we think of a clever way to help users do this instead of having to type `c(month.abb, month.abb[1:6])` like a helper that rep's them an appropriate number of times? (Need not be new func, just example of how to do ok that is simple and non-programmery!)

**Comment by aaronrudkin** [comment] 2018-01-29 17:43
Okay, so before addressing this, I'm going to make the error message here clearer by noting which variable, what the length is, and what N is. In the MWE this doesn't make a difference but it'd be useful for users in more complex use cases who might not be aware where the problem is.

To the issue directly: I think in the last pre-Aaron version of fabricatr we did do automatic wrapping like this; the problem was, of course, that this behaviour was non-transparent to the user and so it wouldn't have been obvious that this was going on. Thus we deliberately added a check for rectangularization. I would oppose any change to that.

I think as you allude to, the compromise would be an explicit helper function. Something like:

```
months = add_level(N = 18, month = pad(month.abb))
```

(Note that I don't know if `pad` is a pre-existing function so it might have to be named something else.)

**Comment by aaronrudkin** [comment] 2018-01-29 20:08
I have code committed for this function, we need only solve the naming issue.

**Closed** 2018-01-30 00:21 UTC
